pipeline {
    agent any
    tools {
        maven "Maven3"
        jdk "OracleJDK8"
    }
    environment {
        cluster = "vproprod"
        service ="vproappprodsvc"
    }
    stages {
        stage('Deploy to ECS staging'){

            steps{
                withAWS(credentials: 'aws', region:'ap-south-1'){
                  sh 'aws ecs update-service --cluster ${cluster} --service ${service} --force-new-deployment'  
                }
            }
        }
    }
    post{
        always {
            echo 'Slack Notifications.'
            slackSend channel: '#jenkinscicd',
            message: "${currentBuild.currentResult}:* Job ${env.JOB_NAME} build ${env.BUILD_NUMBER} /n"
        }
    }   
}   